# Generated by Django 3.1 on 2020-08-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200831_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Management', 'verbose_name_plural': 'User Management'},
        ),
    ]
